### ISSUE TITLE
Predict all audios as fake

### ISSUE THREAD

**Issue by msapy** [UNICT-Fake-Audio/fake-audio-detector#4]
Hey I have been trying some samples but unfortunately the output is always fake. Below there are one fake and one real wav files where I get from ASVSpoof 2019 Dataset. What might have been the issue.

[real and fake audios.zip](https://github.com/UNICT-Fake-Audio/fake-audio-detector/files/9961886/real.and.fake.audios.zip)

**Comment by DIN05AUR** [comment]
Does this repo contain full length code? Or it is just the part of a code, because there are just few files (just 3 .py files) and when I tried running it, it shows error FILE_PATH = sys.argv[1]
RuntimeWarning: Couldn't find ffmpeg or avconv..........................IndexError: list index out of range

**Comment by Helias** [comment]
Hope to release new models with a confusion matrix so you can check if there are any false negative/positive before using the model and verify it properly on your local machine
